# Generated by Django 2.2.9 on 2020-06-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_status',
            field=models.CharField(choices=[('IN', 'Inprogress'), ('CP', 'Complete')], default='IN', max_length=2),
        ),
    ]
