# Generated by Django 2.2.9 on 2020-06-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tasks_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_time',
            field=models.IntegerField(default=0),
        ),
    ]
